Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.ssh.insert_key = false

  team_login = "fli"

  config.vm.synced_folder "confs/", "/vagrant_manifests"

  config.vm.define "#{team_login}S" do |server|
    server.vm.hostname = "#{team_login}S"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      # vb.gui = true
    end

    server.vm.provision "shell", path: "scripts/provision-server.sh", args:["192.168.56.110"]
  end

end