apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Application 1</title>
      <style>
        body { font-family: sans-serif; background-color: #e0f2f7; color: #004d40; text-align: center; padding-top: 100px; }
        h1 { color: #00796b; }
      </style>
    </head>
    <body>
      <h1>Welcome to Application 1!</h1>
      <p>Accessed via app1.com</p>
    </body>
    </html>
