Vagrant.configure("2") do |config|

  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.ssh.insert_key = false

  team_login = "fli"

  # config.vm.synced_folder "./data", "/vagrant_data", create: true
  config.vm.synced_folder "./k3s_shared_data", "/var/lib/k3s_shared", create: true, owner: "root", group: "root", mount_options: ["dmode=777", "fmode=777"]

  config.vm.define "#{team_login}S" do |server|
    server.vm.hostname = "#{team_login}S"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    server.vm.provision "shell", path: "scripts/provision-server.sh", args: ["/var/lib/k3s_shared/k3s_token"]
  end

  config.vm.define "#{team_login}SW" do |worker|
    worker.vm.hostname = "#{team_login}SW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    worker.vm.provision "shell", path: "scripts/provision-worker.sh", args: ["192.168.56.110", "/var/lib/k3s_shared/k3s_token"]
  end

end