Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.ssh.insert_key = false

  team_login = "fli"
  k3s_version = "v1.33.1+k3s1"

  config.vm.synced_folder "./data", "/vagrant_data", create: true

  config.vm.define "#{team_login}S" do |server|
    server.vm.hostname = "#{team_login}S"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    server.vm.provision "shell", path: "scripts/provision-server.sh", args: k3s_version
  end

  config.vm.define "#{team_login}SW" do |worker|
    worker.vm.hostname = "#{team_login}SW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
    end

    worker.vm.provision "shell", path: "scripts/provision-worker.sh", args: ["192.168.56.110", k3s_version]
  end

end